CREATE TABLE DEPARTMENT4
AS SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT4;

-- DEPARTMENT4 테이블에 'D0', '기획개발팀', 'L2' 삽입
INSERT INTO DEPARTMENT4
VALUES('D0', '기획개발팀', 'L2');
--> 실행 결과로 삽입된 행의 개수 반환

-- 사용자(개발자) 직법 트랜잭션 제어 처리
COMMIT;
ROLLBACK;

UPDATE DEPARTMENT4
SET DEPT_TITLE = '기획개발팀'
WHERE DEPT_ID = 'D0';

SELECT COUNT(*) FROM DEPARTMENT4 d 
WHERE d.DEPT_ID = ?;


--DEPARTMENT4 테이블 조회 <- 복사한 테이블 NOT NULL을 제외한 제약 조건이 복사 X, PK 제약 조건이 없는 상태
SELECT * FROM DEPARTMENT4 d;
DELETE FROM DEPARTMENT4 WHERE DEPT_ID = 'D6';

-- DEPARTMENT4 테이블에 PK 제약조건 추가
ALTER TABLE DEPARTMENT4
ADD CONSTRAINT DEPT4_PK
PRIMARY KEY(DEPT_ID);

--INSERT INTO 테이블명 (서브쿼리) -- N행

DELETE FROM DEPARTMENT4 WHERE DEPT_ID = 'B3';

UPDATE DEPARTMENT4
SET DEPT_TITLE = '개발팀' , LOCATION_ID = 'L1'
WHERE DEPT_ID = 'B1';

SELECT *
FROM DEPARTMENT4
WHERE DEPT_TITLE LIKE '%인%';